// Built-in database of foods commonly eaten in Thailand.
// Nutrition values are approximate, per the stated serving.
// kcal = calories, p = protein (g), c = carbohydrates (g), f = fat (g)
const FOOD_DB = [
  // ----- Rice dishes -----
  { id: "rice-steamed",   name: "Steamed jasmine rice", thai: "ข้าวสวย", cat: "Rice dishes", serving: "1 plate (200 g)", kcal: 260, p: 5,  c: 57, f: 0.5 },
  { id: "rice-brown",     name: "Brown rice", thai: "ข้าวกล้อง", cat: "Rice dishes", serving: "1 plate (200 g)", kcal: 230, p: 5,  c: 48, f: 1.8 },
  { id: "rice-sticky",    name: "Sticky rice", thai: "ข้าวเหนียว", cat: "Rice dishes", serving: "1 pack (150 g)", kcal: 245, p: 4.5, c: 54, f: 0.4 },
  { id: "rice-fried",     name: "Fried rice with pork", thai: "ข้าวผัดหมู", cat: "Rice dishes", serving: "1 plate", kcal: 520, p: 18, c: 68, f: 19 },
  { id: "rice-crab",      name: "Crab fried rice", thai: "ข้าวผัดปู", cat: "Rice dishes", serving: "1 plate", kcal: 500, p: 20, c: 66, f: 17 },
  { id: "khao-man-gai",   name: "Khao man gai (chicken rice)", thai: "ข้าวมันไก่", cat: "Rice dishes", serving: "1 plate", kcal: 600, p: 30, c: 75, f: 20 },
  { id: "khao-moo-daeng", name: "Red pork on rice", thai: "ข้าวหมูแดง", cat: "Rice dishes", serving: "1 plate", kcal: 560, p: 25, c: 72, f: 18 },
  { id: "khao-moo-krob",  name: "Crispy pork on rice", thai: "ข้าวหมูกรอบ", cat: "Rice dishes", serving: "1 plate", kcal: 650, p: 22, c: 65, f: 33 },
  { id: "khao-kha-moo",   name: "Braised pork leg on rice", thai: "ข้าวขาหมู", cat: "Rice dishes", serving: "1 plate", kcal: 690, p: 28, c: 70, f: 32 },
  { id: "khao-krapow",    name: "Basil pork rice + fried egg", thai: "ข้าวกะเพราหมูสับไข่ดาว", cat: "Rice dishes", serving: "1 plate", kcal: 630, p: 28, c: 62, f: 30 },
  { id: "khao-krapow-gai",name: "Basil chicken rice", thai: "ข้าวกะเพราไก่", cat: "Rice dishes", serving: "1 plate", kcal: 500, p: 27, c: 60, f: 17 },
  { id: "khao-tom-moo",   name: "Rice soup with pork", thai: "ข้าวต้มหมู", cat: "Rice dishes", serving: "1 bowl", kcal: 250, p: 14, c: 38, f: 5 },
  { id: "jok-moo",        name: "Congee with pork & egg", thai: "โจ๊กหมูใส่ไข่", cat: "Rice dishes", serving: "1 bowl", kcal: 300, p: 16, c: 40, f: 8 },
  { id: "khao-niew-gai",  name: "Sticky rice + grilled chicken", thai: "ข้าวเหนียวไก่ย่าง", cat: "Rice dishes", serving: "1 set", kcal: 540, p: 32, c: 58, f: 20 },
  { id: "khao-omelet",    name: "Omelet on rice", thai: "ข้าวไข่เจียว", cat: "Rice dishes", serving: "1 plate", kcal: 480, p: 15, c: 60, f: 20 },
  { id: "american-fried-rice", name: "American fried rice", thai: "ข้าวผัดอเมริกัน", cat: "Rice dishes", serving: "1 plate", kcal: 720, p: 24, c: 82, f: 32 },

  // ----- Noodles -----
  { id: "pad-thai",       name: "Pad thai with shrimp", thai: "ผัดไทยกุ้งสด", cat: "Noodles", serving: "1 plate", kcal: 570, p: 20, c: 72, f: 22 },
  { id: "pad-see-ew",     name: "Pad see ew with pork", thai: "ผัดซีอิ๊วหมู", cat: "Noodles", serving: "1 plate", kcal: 520, p: 19, c: 66, f: 20 },
  { id: "rad-na",         name: "Rad na (noodles in gravy)", thai: "ราดหน้าหมู", cat: "Noodles", serving: "1 plate", kcal: 440, p: 18, c: 58, f: 15 },
  { id: "pad-kee-mao",    name: "Drunken noodles", thai: "ผัดขี้เมา", cat: "Noodles", serving: "1 plate", kcal: 490, p: 20, c: 58, f: 20 },
  { id: "noodle-clear",   name: "Clear noodle soup with pork", thai: "ก๋วยเตี๋ยวหมูน้ำใส", cat: "Noodles", serving: "1 bowl", kcal: 350, p: 18, c: 48, f: 9 },
  { id: "noodle-tomyum",  name: "Tom yum noodles", thai: "ก๋วยเตี๋ยวต้มยำ", cat: "Noodles", serving: "1 bowl", kcal: 430, p: 19, c: 52, f: 16 },
  { id: "boat-noodles",   name: "Boat noodles", thai: "ก๋วยเตี๋ยวเรือ", cat: "Noodles", serving: "1 bowl", kcal: 380, p: 18, c: 45, f: 14 },
  { id: "bamee-moo-daeng",name: "Egg noodles with red pork", thai: "บะหมี่หมูแดง", cat: "Noodles", serving: "1 bowl", kcal: 420, p: 20, c: 55, f: 13 },
  { id: "bamee-kiew",     name: "Wonton noodle soup", thai: "บะหมี่เกี๊ยวหมู", cat: "Noodles", serving: "1 bowl", kcal: 400, p: 20, c: 50, f: 13 },
  { id: "khao-soi",       name: "Khao soi with chicken", thai: "ข้าวซอยไก่", cat: "Noodles", serving: "1 bowl", kcal: 600, p: 24, c: 55, f: 32 },
  { id: "kanom-jeen",     name: "Kanom jeen nam ya", thai: "ขนมจีนน้ำยา", cat: "Noodles", serving: "1 plate", kcal: 380, p: 15, c: 55, f: 11 },
  { id: "yen-ta-fo",      name: "Yen ta fo", thai: "เย็นตาโฟ", cat: "Noodles", serving: "1 bowl", kcal: 350, p: 18, c: 48, f: 9 },
  { id: "kuay-jab",       name: "Kuay jab with crispy pork", thai: "ก๋วยจั๊บหมูกรอบ", cat: "Noodles", serving: "1 bowl", kcal: 420, p: 16, c: 45, f: 20 },
  { id: "suki-nam",       name: "Suki soup with pork", thai: "สุกี้น้ำหมู", cat: "Noodles", serving: "1 bowl", kcal: 320, p: 22, c: 30, f: 12 },
  { id: "suki-haeng",     name: "Suki stir-fried", thai: "สุกี้แห้ง", cat: "Noodles", serving: "1 plate", kcal: 390, p: 22, c: 32, f: 18 },
  { id: "mama-tom",       name: "Instant noodles (cooked)", thai: "มาม่าต้ม", cat: "Noodles", serving: "1 pack", kcal: 350, p: 8, c: 46, f: 15 },
  { id: "woonsen-obb",    name: "Glass noodles baked with shrimp", thai: "กุ้งอบวุ้นเส้น", cat: "Noodles", serving: "1 serving", kcal: 300, p: 18, c: 38, f: 9 },

  // ----- Curries & soups -----
  { id: "green-curry",    name: "Green curry with chicken", thai: "แกงเขียวหวานไก่", cat: "Curries & soups", serving: "1 bowl (no rice)", kcal: 340, p: 20, c: 12, f: 25 },
  { id: "red-curry",      name: "Red curry with pork", thai: "แกงเผ็ดหมู", cat: "Curries & soups", serving: "1 bowl (no rice)", kcal: 320, p: 19, c: 10, f: 24 },
  { id: "panang",         name: "Panang curry with pork", thai: "พะแนงหมู", cat: "Curries & soups", serving: "1 bowl (no rice)", kcal: 350, p: 20, c: 11, f: 26 },
  { id: "massaman",       name: "Massaman curry with chicken", thai: "แกงมัสมั่นไก่", cat: "Curries & soups", serving: "1 bowl (no rice)", kcal: 480, p: 22, c: 28, f: 32 },
  { id: "kaeng-som",      name: "Sour curry with vegetables", thai: "แกงส้มผักรวม", cat: "Curries & soups", serving: "1 bowl", kcal: 130, p: 12, c: 12, f: 3 },
  { id: "kaeng-liang",    name: "Kaeng liang (herbal soup)", thai: "แกงเลียง", cat: "Curries & soups", serving: "1 bowl", kcal: 90, p: 8, c: 9, f: 2 },
  { id: "tom-yum-goong",  name: "Tom yum goong (clear)", thai: "ต้มยำกุ้งน้ำใส", cat: "Curries & soups", serving: "1 bowl", kcal: 180, p: 20, c: 8, f: 7 },
  { id: "tom-yum-cream",  name: "Tom yum goong (creamy)", thai: "ต้มยำกุ้งน้ำข้น", cat: "Curries & soups", serving: "1 bowl", kcal: 290, p: 20, c: 12, f: 18 },
  { id: "tom-kha-gai",    name: "Tom kha gai", thai: "ต้มข่าไก่", cat: "Curries & soups", serving: "1 bowl", kcal: 350, p: 18, c: 10, f: 28 },
  { id: "kaeng-jued",     name: "Clear soup, tofu & minced pork", thai: "แกงจืดเต้าหู้หมูสับ", cat: "Curries & soups", serving: "1 bowl", kcal: 150, p: 14, c: 6, f: 8 },
  { id: "tom-saeb",       name: "Tom saeb (Isaan sour soup)", thai: "ต้มแซ่บกระดูกอ่อน", cat: "Curries & soups", serving: "1 bowl", kcal: 220, p: 18, c: 6, f: 14 },
  { id: "hor-mok",        name: "Hor mok (curried fish custard)", thai: "ห่อหมกปลา", cat: "Curries & soups", serving: "1 cup", kcal: 240, p: 18, c: 8, f: 16 },

  // ----- Stir-fries & mains -----
  { id: "pad-krapow-moo", name: "Stir-fried basil minced pork", thai: "ผัดกะเพราหมูสับ", cat: "Stir-fries & mains", serving: "1 serving (no rice)", kcal: 370, p: 23, c: 8, f: 27 },
  { id: "pad-pak-bung",   name: "Stir-fried morning glory", thai: "ผัดผักบุ้งไฟแดง", cat: "Stir-fries & mains", serving: "1 plate", kcal: 180, p: 5, c: 10, f: 14 },
  { id: "pad-pak-ruam",   name: "Stir-fried mixed vegetables", thai: "ผัดผักรวม", cat: "Stir-fries & mains", serving: "1 plate", kcal: 140, p: 5, c: 12, f: 9 },
  { id: "pad-prik-kaeng", name: "Stir-fried curry paste pork", thai: "ผัดพริกแกงหมู", cat: "Stir-fries & mains", serving: "1 serving", kcal: 330, p: 20, c: 9, f: 24 },
  { id: "moo-tod-katiem", name: "Garlic pepper fried pork", thai: "หมูทอดกระเทียม", cat: "Stir-fries & mains", serving: "1 serving", kcal: 400, p: 25, c: 8, f: 30 },
  { id: "kai-jeow",       name: "Thai omelet", thai: "ไข่เจียว", cat: "Stir-fries & mains", serving: "1 egg omelet", kcal: 250, p: 10, c: 2, f: 22 },
  { id: "kai-dao",        name: "Fried egg", thai: "ไข่ดาว", cat: "Stir-fries & mains", serving: "1 egg", kcal: 90, p: 6, c: 0.5, f: 7 },
  { id: "kai-tom",        name: "Boiled egg", thai: "ไข่ต้ม", cat: "Stir-fries & mains", serving: "1 egg", kcal: 75, p: 6, c: 0.6, f: 5 },
  { id: "pla-nin-tod",    name: "Fried tilapia", thai: "ปลานิลทอด", cat: "Stir-fries & mains", serving: "1 medium fish", kcal: 360, p: 40, c: 2, f: 21 },
  { id: "pla-kapong-neung", name: "Steamed sea bass, lime sauce", thai: "ปลากะพงนึ่งมะนาว", cat: "Stir-fries & mains", serving: "half fish", kcal: 220, p: 38, c: 4, f: 5 },
  { id: "goong-chae",     name: "Shrimp in fish sauce", thai: "กุ้งแช่น้ำปลา", cat: "Stir-fries & mains", serving: "1 plate", kcal: 150, p: 26, c: 4, f: 3 },
  { id: "chicken-breast", name: "Grilled chicken breast", thai: "อกไก่ย่าง", cat: "Stir-fries & mains", serving: "100 g", kcal: 165, p: 31, c: 0, f: 3.6 },
  { id: "tofu-100",       name: "Firm tofu", thai: "เต้าหู้แข็ง", cat: "Stir-fries & mains", serving: "100 g", kcal: 80, p: 8, c: 2, f: 4.5 },

  // ----- Salads (Yum) -----
  { id: "som-tam-thai",   name: "Som tam Thai (papaya salad)", thai: "ส้มตำไทย", cat: "Salads", serving: "1 plate", kcal: 120, p: 4, c: 22, f: 2.5 },
  { id: "som-tam-poo",    name: "Som tam with fermented crab", thai: "ส้มตำปูปลาร้า", cat: "Salads", serving: "1 plate", kcal: 130, p: 6, c: 20, f: 3 },
  { id: "larb-moo",       name: "Larb moo (spicy pork salad)", thai: "ลาบหมู", cat: "Salads", serving: "1 plate", kcal: 260, p: 22, c: 8, f: 16 },
  { id: "nam-tok-moo",    name: "Nam tok moo (grilled pork salad)", thai: "น้ำตกหมู", cat: "Salads", serving: "1 plate", kcal: 250, p: 24, c: 7, f: 14 },
  { id: "yum-woonsen",    name: "Glass noodle salad", thai: "ยำวุ้นเส้น", cat: "Salads", serving: "1 plate", kcal: 220, p: 14, c: 30, f: 5 },
  { id: "yum-mama",       name: "Instant noodle salad", thai: "ยำมาม่า", cat: "Salads", serving: "1 plate", kcal: 330, p: 14, c: 40, f: 13 },
  { id: "yum-talay",      name: "Spicy seafood salad", thai: "ยำทะเล", cat: "Salads", serving: "1 plate", kcal: 180, p: 24, c: 10, f: 5 },
  { id: "pla-goong",      name: "Spicy shrimp salad with herbs", thai: "พล่ากุ้ง", cat: "Salads", serving: "1 plate", kcal: 160, p: 22, c: 8, f: 4 },
  { id: "yum-kai-dao",    name: "Fried egg salad", thai: "ยำไข่ดาว", cat: "Salads", serving: "1 plate", kcal: 280, p: 13, c: 12, f: 20 },

  // ----- Grilled & street food -----
  { id: "gai-yang",       name: "Grilled chicken thigh", thai: "ไก่ย่าง (น่อง)", cat: "Grilled & street food", serving: "1 piece", kcal: 290, p: 25, c: 2, f: 20 },
  { id: "moo-ping",       name: "Moo ping (grilled pork skewer)", thai: "หมูปิ้ง", cat: "Grilled & street food", serving: "1 skewer", kcal: 110, p: 7, c: 4, f: 7 },
  { id: "kor-moo-yang",   name: "Grilled pork neck", thai: "คอหมูย่าง", cat: "Grilled & street food", serving: "1 plate (150 g)", kcal: 400, p: 27, c: 2, f: 32 },
  { id: "look-chin-ping", name: "Grilled meatball skewer", thai: "ลูกชิ้นปิ้ง", cat: "Grilled & street food", serving: "1 skewer (4 balls)", kcal: 90, p: 6, c: 5, f: 5 },
  { id: "sai-krok",       name: "Sai krok Isaan (2 pcs)", thai: "ไส้กรอกอีสาน", cat: "Grilled & street food", serving: "2 pieces", kcal: 220, p: 9, c: 10, f: 16 },
  { id: "moo-satay",      name: "Pork satay (5 sticks)", thai: "หมูสะเต๊ะ", cat: "Grilled & street food", serving: "5 sticks + sauce", kcal: 350, p: 22, c: 16, f: 22 },
  { id: "pla-muek-yang",  name: "Grilled squid", thai: "ปลาหมึกย่าง", cat: "Grilled & street food", serving: "1 medium", kcal: 130, p: 24, c: 3, f: 2 },
  { id: "tod-man-pla",    name: "Fish cakes (4 pcs)", thai: "ทอดมันปลา", cat: "Grilled & street food", serving: "4 pieces", kcal: 260, p: 16, c: 12, f: 16 },
  { id: "por-pia-tod",    name: "Fried spring rolls (2 pcs)", thai: "ปอเปี๊ยะทอด", cat: "Grilled & street food", serving: "2 rolls", kcal: 220, p: 6, c: 22, f: 12 },
  { id: "gai-tod",        name: "Fried chicken (1 pc)", thai: "ไก่ทอด", cat: "Grilled & street food", serving: "1 piece", kcal: 290, p: 21, c: 10, f: 18 },
  { id: "nam-nueng",      name: "Nam nueng set", thai: "แหนมเนือง", cat: "Grilled & street food", serving: "1 roll", kcal: 90, p: 6, c: 9, f: 3 },
  { id: "kiew-tod",       name: "Fried wontons (5 pcs)", thai: "เกี๊ยวทอด", cat: "Grilled & street food", serving: "5 pieces", kcal: 240, p: 8, c: 20, f: 14 },

  // ----- Desserts -----
  { id: "mango-sticky",   name: "Mango sticky rice", thai: "ข้าวเหนียวมะม่วง", cat: "Desserts", serving: "1 plate", kcal: 480, p: 7, c: 85, f: 13 },
  { id: "tab-tim-grob",   name: "Tab tim grob (water chestnut)", thai: "ทับทิมกรอบ", cat: "Desserts", serving: "1 bowl", kcal: 300, p: 2, c: 45, f: 12 },
  { id: "bua-loy",        name: "Bua loy in coconut milk", thai: "บัวลอย", cat: "Desserts", serving: "1 bowl", kcal: 280, p: 4, c: 40, f: 12 },
  { id: "kluay-buat-chee",name: "Banana in coconut milk", thai: "กล้วยบวชชี", cat: "Desserts", serving: "1 bowl", kcal: 300, p: 3, c: 45, f: 13 },
  { id: "kanom-krok",     name: "Kanom krok (4 pairs)", thai: "ขนมครก", cat: "Desserts", serving: "8 pieces", kcal: 240, p: 3, c: 30, f: 12 },
  { id: "roti-milk",      name: "Roti with condensed milk", thai: "โรตีใส่นม", cat: "Desserts", serving: "1 piece", kcal: 400, p: 6, c: 48, f: 20 },
  { id: "lod-chong",      name: "Lod chong in coconut milk", thai: "ลอดช่องน้ำกะทิ", cat: "Desserts", serving: "1 bowl", kcal: 260, p: 2, c: 40, f: 10 },
  { id: "coconut-icecream", name: "Coconut ice cream", thai: "ไอศกรีมกะทิ", cat: "Desserts", serving: "1 cup", kcal: 200, p: 2, c: 24, f: 11 },
  { id: "patongko",       name: "Patongko (2 pcs)", thai: "ปาท่องโก๋", cat: "Desserts", serving: "2 pieces", kcal: 180, p: 3, c: 20, f: 10 },
  { id: "kanom-buang",    name: "Kanom buang (2 pcs)", thai: "ขนมเบื้อง", cat: "Desserts", serving: "2 pieces", kcal: 140, p: 2, c: 22, f: 5 },
  { id: "chao-kuay",      name: "Grass jelly with syrup", thai: "เฉาก๊วย", cat: "Desserts", serving: "1 bowl", kcal: 120, p: 0.5, c: 30, f: 0 },
  { id: "sangkaya-fakthong", name: "Pumpkin custard", thai: "สังขยาฟักทอง", cat: "Desserts", serving: "1 slice", kcal: 160, p: 4, c: 24, f: 6 },
  { id: "khao-niew-sangkaya", name: "Sticky rice with custard", thai: "ข้าวเหนียวสังขยา", cat: "Desserts", serving: "1 pack", kcal: 380, p: 6, c: 65, f: 11 },

  // ----- Drinks -----
  { id: "thai-tea",       name: "Thai iced tea", thai: "ชาเย็น", cat: "Drinks", serving: "1 cup (16 oz)", kcal: 260, p: 3, c: 40, f: 10 },
  { id: "green-tea-milk", name: "Iced green tea with milk", thai: "ชาเขียวเย็น", cat: "Drinks", serving: "1 cup (16 oz)", kcal: 240, p: 3, c: 38, f: 9 },
  { id: "iced-coffee",    name: "Thai iced coffee", thai: "กาแฟเย็น", cat: "Drinks", serving: "1 cup (16 oz)", kcal: 180, p: 3, c: 28, f: 7 },
  { id: "oliang",         name: "Oliang (black iced coffee)", thai: "โอเลี้ยง", cat: "Drinks", serving: "1 cup", kcal: 90, p: 0, c: 22, f: 0 },
  { id: "americano-iced", name: "Iced americano (no sugar)", thai: "อเมริกาโน่เย็น", cat: "Drinks", serving: "1 cup", kcal: 10, p: 0.5, c: 1, f: 0 },
  { id: "cocoa-iced",     name: "Iced cocoa", thai: "โกโก้เย็น", cat: "Drinks", serving: "1 cup (16 oz)", kcal: 250, p: 5, c: 35, f: 10 },
  { id: "nom-yen",        name: "Nom yen (pink milk)", thai: "นมเย็น", cat: "Drinks", serving: "1 cup", kcal: 220, p: 5, c: 34, f: 7 },
  { id: "coconut-water",  name: "Fresh coconut water", thai: "น้ำมะพร้าว", cat: "Drinks", serving: "1 coconut", kcal: 60, p: 1, c: 14, f: 0 },
  { id: "orange-juice",   name: "Fresh orange juice", thai: "น้ำส้มคั้น", cat: "Drinks", serving: "1 bottle (250 ml)", kcal: 110, p: 1.5, c: 25, f: 0 },
  { id: "lemon-tea",      name: "Iced lemon tea", thai: "ชามะนาว", cat: "Drinks", serving: "1 cup", kcal: 120, p: 0, c: 30, f: 0 },
  { id: "soy-milk",       name: "Soy milk with sugar", thai: "น้ำเต้าหู้", cat: "Drinks", serving: "1 bag/cup", kcal: 120, p: 6, c: 16, f: 4 },
  { id: "milk-plain",     name: "Plain milk", thai: "นมจืด", cat: "Drinks", serving: "1 glass (200 ml)", kcal: 130, p: 7, c: 10, f: 7 },
  { id: "water",          name: "Water", thai: "น้ำเปล่า", cat: "Drinks", serving: "1 glass", kcal: 0, p: 0, c: 0, f: 0 },
  { id: "beer",           name: "Beer (1 can)", thai: "เบียร์", cat: "Drinks", serving: "330 ml", kcal: 150, p: 1, c: 12, f: 0 },
  { id: "bubble-tea",     name: "Bubble milk tea", thai: "ชานมไข่มุก", cat: "Drinks", serving: "1 cup (16 oz)", kcal: 340, p: 4, c: 55, f: 12 },

  // ----- Fruits -----
  { id: "mango-ripe",     name: "Ripe mango", thai: "มะม่วงสุก", cat: "Fruits", serving: "half fruit", kcal: 100, p: 1, c: 25, f: 0.5 },
  { id: "banana",         name: "Banana (kluay hom)", thai: "กล้วยหอม", cat: "Fruits", serving: "1 fruit", kcal: 105, p: 1.3, c: 27, f: 0.4 },
  { id: "banana-namwa",   name: "Banana (kluay nam wa)", thai: "กล้วยน้ำว้า", cat: "Fruits", serving: "1 fruit", kcal: 60, p: 0.8, c: 15, f: 0.2 },
  { id: "watermelon",     name: "Watermelon", thai: "แตงโม", cat: "Fruits", serving: "1 cup, cubed", kcal: 50, p: 1, c: 12, f: 0.2 },
  { id: "pineapple",      name: "Pineapple", thai: "สับปะรด", cat: "Fruits", serving: "1 cup, cubed", kcal: 60, p: 0.7, c: 15, f: 0.1 },
  { id: "guava",          name: "Guava", thai: "ฝรั่ง", cat: "Fruits", serving: "half fruit", kcal: 70, p: 2, c: 15, f: 0.5 },
  { id: "papaya",         name: "Ripe papaya", thai: "มะละกอสุก", cat: "Fruits", serving: "1 cup, cubed", kcal: 55, p: 0.6, c: 14, f: 0.2 },
  { id: "mangosteen",     name: "Mangosteen (3 fruits)", thai: "มังคุด", cat: "Fruits", serving: "3 fruits", kcal: 70, p: 0.6, c: 17, f: 0.4 },
  { id: "durian",         name: "Durian (2 pods)", thai: "ทุเรียน", cat: "Fruits", serving: "2 pods (100 g)", kcal: 270, p: 2.5, c: 33, f: 13 },
  { id: "rambutan",       name: "Rambutan (5 fruits)", thai: "เงาะ", cat: "Fruits", serving: "5 fruits", kcal: 60, p: 0.7, c: 15, f: 0.2 },
  { id: "longan",         name: "Longan (10 fruits)", thai: "ลำไย", cat: "Fruits", serving: "10 fruits", kcal: 60, p: 1, c: 15, f: 0.1 },
  { id: "rose-apple",     name: "Rose apple", thai: "ชมพู่", cat: "Fruits", serving: "2 fruits", kcal: 40, p: 0.5, c: 9, f: 0.2 },
  { id: "dragon-fruit",   name: "Dragon fruit", thai: "แก้วมังกร", cat: "Fruits", serving: "half fruit", kcal: 60, p: 1.2, c: 13, f: 0.4 },
  { id: "orange-som",     name: "Orange (som)", thai: "ส้ม", cat: "Fruits", serving: "1 fruit", kcal: 60, p: 1, c: 15, f: 0.2 },
  { id: "pomelo",         name: "Pomelo (3 segments)", thai: "ส้มโอ", cat: "Fruits", serving: "3 segments", kcal: 60, p: 1, c: 15, f: 0 },

  // ----- Bakery & snacks -----
  { id: "bread-slice",    name: "White bread", thai: "ขนมปังแผ่น", cat: "Bakery & snacks", serving: "1 slice", kcal: 80, p: 2.5, c: 15, f: 1 },
  { id: "sandwich-ham",   name: "Ham cheese sandwich", thai: "แซนด์วิชแฮมชีส", cat: "Bakery & snacks", serving: "1 piece", kcal: 300, p: 13, c: 32, f: 13 },
  { id: "toast-butter",   name: "Butter sugar toast", thai: "ขนมปังปิ้งเนยน้ำตาล", cat: "Bakery & snacks", serving: "1 slice", kcal: 200, p: 3, c: 24, f: 10 },
  { id: "salapao",        name: "Salapao (pork bun)", thai: "ซาลาเปาไส้หมู", cat: "Bakery & snacks", serving: "1 bun", kcal: 220, p: 8, c: 32, f: 6 },
  { id: "kanom-jeeb",     name: "Kanom jeeb (4 pcs)", thai: "ขนมจีบ", cat: "Bakery & snacks", serving: "4 pieces", kcal: 190, p: 10, c: 14, f: 10 },
  { id: "yogurt-cup",     name: "Yogurt", thai: "โยเกิร์ต", cat: "Bakery & snacks", serving: "1 cup (135 g)", kcal: 130, p: 4, c: 20, f: 3.5 },
  { id: "seaweed-snack",  name: "Seaweed snack", thai: "สาหร่ายทอด", cat: "Bakery & snacks", serving: "1 pack (small)", kcal: 90, p: 2, c: 6, f: 6 },
  { id: "potato-chips",   name: "Potato chips", thai: "มันฝรั่งทอดกรอบ", cat: "Bakery & snacks", serving: "1 small bag (30 g)", kcal: 160, p: 2, c: 15, f: 10 },
  { id: "cashews",        name: "Roasted cashew nuts", thai: "เม็ดมะม่วงหิมพานต์", cat: "Bakery & snacks", serving: "1 handful (28 g)", kcal: 160, p: 5, c: 9, f: 13 },
  { id: "khao-lam",       name: "Khao lam (bamboo sticky rice)", thai: "ข้าวหลาม", cat: "Bakery & snacks", serving: "1 tube (small)", kcal: 330, p: 5, c: 60, f: 8 },
];
